name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      packages: write

    steps:
      - name: Clear workspace
        uses: chick-fil-a/gha-clear-workspace@v1
      - name: Checkout project
        uses: actions/checkout@v4
      - run: |
          sudo chmod -R ugo+rwX .
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Build with Maven
        run: mvn -B release:prepare release:perform --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Update CHANGELOG.md
        id: changelog
        uses: Requarks/changelog-action@v1.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get-latest-tag.outputs.tag }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          commit_message: 'docs: update CHANGELOG.md for ${{ steps.get-latest-tag.outputs.tag }} [skip ci]'
          file_pattern: CHANGELOG.md
